language: python
dist: xenial
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.7
    env: TOXENV=styleck
  - python: 3.7
    env: TOXENV=typeck

install:
  - pip install tox

script: tox
